services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: zoonmoon/saas-ymm-bigc:v13
    env_file: 
    - path: "./env" 
      required: true
    - path: "./env.production"
      required: true
    ports:
      - 3000:3000