import { fetchStoreData } from "../indexing/fitment-data/fetch_store_data"
import { bigCScriptsCreatedUsingThisAccessToken } from "./script-manager/utils"
import { requiredScripts } from "./script-manager/data"

export async function GET(request, {params}){

    // returns scripts and widgets generated by the access token of this store

    try{    
        
        const {store_hash} = await params 
        
        const {access_token} = await fetchStoreData(store_hash)

        let scripts = await bigCScriptsCreatedUsingThisAccessToken(store_hash, access_token)    

        let scriptsAlreadyCreated  = scripts.map(({name}) => name )

        let all_scripts_already_created =  requiredScripts.every(reqScript => scriptsAlreadyCreated.includes(reqScript))
        
        return new Response(JSON.stringify({success: true, scripts, requiredScripts, all_scripts_already_created}))
        
    }catch(error){

        return new Response(JSON.stringify({success: false, message: error.message}))
    
    }

}